project_id = "ycmhgmxstrjoiysbbpxh"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-admin-invite]
    verify_jwt = true
  [functions.bling-oauth-callback]
    verify_jwt = false
