
INSERT INTO public.site_content_sections (section_key, title, subtitle, description, cta_label, cta_link, image_url, items, active)
VALUES
  ('hero_banner', null, null, null, 'Comprar agora', '#produtos', null, '[{"title":"Whey Isolado Horen","subtitle":"LANÇAMENTO","description":"30% OFF no nosso novo Whey Protein Isolado. Performance máxima com sabor premium.","cta":"Comprar agora","link":"#produtos","image_url":""},
  {"title":"Combo Performance","subtitle":"OFERTA ESPECIAL","description":"Whey + Creatina por apenas R$ 349,90. O kit perfeito para evoluir seus resultados.","cta":"Ver combo","link":"#produtos","image_url":""},
  {"title":"Kits Exclusivos","subtitle":"PROMOÇÃO","description":"Kits com frete grátis em compras acima de R$ 299. Receba sem custo de envio.","cta":"Aproveitar","link":"#produtos","image_url":""}]'::jsonb, true),
  ('promo_banner', 'Promoções', null, null, null, null, null, '[{"text":"🔥 LANÇAMENTO — Whey Isolado Horen com 30% OFF","link":"#produtos"},{"text":"🎁 COMBO PERFORMANCE — Whey + Creatina por R$ 349,90","link":"#produtos"},{"text":"🚚 FRETE GRÁTIS em compras acima de R$ 299","link":"#produtos"},{"text":"⚡ KIT INICIANTE — 3 suplementos essenciais por R$ 449,90","link":"#produtos"}]'::jsonb, true),
  ('about_section', 'Quem somos', 'Sobre a Horen', 'Horen é uma marca brasileira de suplementação esportiva criada para quem busca performance, transparência e resultados reais. Nossos produtos são desenvolvidos com rigor científico e ingredientes de alta qualidade.', null, null, null, '[{"title":"Confiança","description":"Produtos testados e aprovados com total transparência de composição."},{"title":"Qualidade","description":"Ingredientes selecionados e processos rigorosos de controle."},{"title":"Resultado","description":"Fórmulas pensadas para entregar o máximo de performance."},{"title":"Suporte","description":"Atendimento especializado para tirar todas as suas dúvidas."}]'::jsonb, true),
  ('products_section', null, 'Nossos Produtos', null, null, null, null, '[]'::jsonb, true),
  ('footer', 'Rodapé', null, null, null, null, null, '[{"type":"email","label":"contato@horen.com.br","href":"mailto:contato@horen.com.br"},{"type":"phone","label":"(11) 99999-9999","href":"tel:+5511999999999"},{"type":"instagram","label":"@horensuplementos","href":"https://instagram.com/horensuplementos"}]'::jsonb, true),
  ('calculators_section', 'Calculadoras', 'Ferramentas Horen', 'Acompanhe seu consumo e seu metabolismo com precisão. Ferramentas pensadas para quem leva resultados a sério.', 'Ver produtos Horen', '/#produtos', null, '[{"kind":"creatina","title":"Duração da Creatina","subtitle":"Estime quanto tempo seu pote dura","cta_size":"lg","label_grams":"Dose diária (g)","label_stock":"Quantidade no pote (g)","label_start":"Data de início","default_grams":"5","default_stock":"300","result_pre":"Vai durar","result_suffix":"dias","result_end_label":"Previsão de término:"},{"kind":"tmb","title":"Taxa Metabólica Basal","subtitle":"Fórmula de Mifflin-St Jeor","label_sex":"Sexo","label_male":"Masculino","label_female":"Feminino","label_weight":"Peso (kg)","label_height":"Altura (cm)","label_age":"Idade","label_activity":"Nível de atividade","opt_sedentary":"Sedentário","opt_light":"Levemente ativo (1-3x/sem)","opt_moderate":"Moderado (3-5x/sem)","opt_active":"Muito ativo (6-7x/sem)","opt_extreme":"Extremamente ativo","result_pre":"Sua TMB","result_suffix":"kcal/dia","result_total_label":"Gasto total estimado:"}]'::jsonb, true)
ON CONFLICT (section_key) DO NOTHING;
